//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YunMa.Excel.Core {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YunMa.Excel.Core.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 只允许中文、英文、大小写字母以及数字 的本地化字符串。
        /// </summary>
        public static string AllowChsEngChar {
            get {
                return ResourceManager.GetString("AllowChsEngChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只允许英文、大小写字母以及数字 的本地化字符串。
        /// </summary>
        public static string AllowEngChar {
            get {
                return ResourceManager.GetString("AllowEngChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板出现未知错误： 的本地化字符串。
        /// </summary>
        public static string AnUnknownErrorOccurredInTheTemplate {
            get {
                return ResourceManager.GetString("AnUnknownErrorOccurredInTheTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用当前方法之前，必须先调用Append方法！ 的本地化字符串。
        /// </summary>
        public static string AppendMethodMustBeBeforeCurrentMethod {
            get {
                return ResourceManager.GetString("AppendMethodMustBeBeforeCurrentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经存在该名字的sheet 的本地化字符串。
        /// </summary>
        public static string ASheetWithTheNameAlreadyExists {
            get {
                return ResourceManager.GetString("ASheetWithTheNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列头重复！ 的本地化字符串。
        /// </summary>
        public static string ColumnHeadRepeat {
            get {
                return ResourceManager.GetString("ColumnHeadRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据不能为空! 的本地化字符串。
        /// </summary>
        public static string DataCannotBeEmpty {
            get {
                return ResourceManager.GetString("DataCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请定义表头！ 的本地化字符串。
        /// </summary>
        public static string DefineTheHeader {
            get {
                return ResourceManager.GetString("DefineTheHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请勿忽略全部表头！ 的本地化字符串。
        /// </summary>
        public static string DoNotIgnoreAllTheHeader {
            get {
                return ResourceManager.GetString("DoNotIgnoreAllTheHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 构建表达式时出错： 的本地化字符串。
        /// </summary>
        public static string ErrorBuildingExpression {
            get {
                return ResourceManager.GetString("ErrorBuildingExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sheet属性没有标注ExcelImporterAttribute特性: 的本地化字符串。
        /// </summary>
        public static string ExcelimporterAttributeFeaturesIsNotAnnotated {
            get {
                return ResourceManager.GetString("ExcelimporterAttributeFeaturesIsNotAnnotated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在数据重复，请检查！所在行： 的本地化字符串。
        /// </summary>
        public static string ExistDuplicateData {
            get {
                return ResourceManager.GetString("ExistDuplicateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不区分大小写，存在数据重复，请检查！所在行： 的本地化字符串。
        /// </summary>
        public static string ExistDuplicateDataNoFixUpper {
            get {
                return ResourceManager.GetString("ExistDuplicateDataNoFixUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅支持导出“.xlsx”，即不支持Excel97-2003! 的本地化字符串。
        /// </summary>
        internal static string ExportingIsOnlySupportedXLSX {
            get {
                return ResourceManager.GetString("ExportingIsOnlySupportedXLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出结果 的本地化字符串。
        /// </summary>
        public static string ExportResult {
            get {
                return ResourceManager.GetString("ExportResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名必须填写！ 的本地化字符串。
        /// </summary>
        public static string FileNameMustBeFilled {
            get {
                return ResourceManager.GetString("FileNameMustBeFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名不能为空！ 的本地化字符串。
        /// </summary>
        internal static string FileNameShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("FileNameShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件路径不能为空! 的本地化字符串。
        /// </summary>
        public static string FilePathCannotBeEmpty {
            get {
                return ResourceManager.GetString("FilePathCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不合法！ 的本地化字符串。
        /// </summary>
        public static string Illegal {
            get {
                return ResourceManager.GetString("Illegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入数据 的本地化字符串。
        /// </summary>
        public static string ImportData {
            get {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入文件不存在! 的本地化字符串。
        /// </summary>
        public static string ImportFileDoesNotExist {
            get {
                return ResourceManager.GetString("ImportFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前导入模板中未找到此字段！ 的本地化字符串。
        /// </summary>
        public static string ImportTemplateNotFoundThisField {
            get {
                return ResourceManager.GetString("ImportTemplateNotFoundThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据格式无效！ 的本地化字符串。
        /// </summary>
        internal static string InvalidDataFormat {
            get {
                return ResourceManager.GetString("InvalidDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大允许导入条数不能超过 的本地化字符串。
        /// </summary>
        public static string MaximumNumberImportsCannotExceeded {
            get {
                return ResourceManager.GetString("MaximumNumberImportsCannotExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅支持导出“.csv”! 的本地化字符串。
        /// </summary>
        internal static string OnlySupportExportingCsv {
            get {
                return ResourceManager.GetString("OnlySupportExportingCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效，请填写正确的日期时间格式！ 的本地化字符串。
        /// </summary>
        public static string PleaseFillInTheCorrectDateAndTimeFormat {
            get {
                return ResourceManager.GetString("PleaseFillInTheCorrectDateAndTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效，请填写正确的小数！ 的本地化字符串。
        /// </summary>
        public static string PleaseFillInTheCorrectDecimal {
            get {
                return ResourceManager.GetString("PleaseFillInTheCorrectDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效，请填写正确的Guid格式！ 的本地化字符串。
        /// </summary>
        public static string PleaseFillInTheCorrectGUIDFormat {
            get {
                return ResourceManager.GetString("PleaseFillInTheCorrectGUIDFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效，请填写正确的整数数值！ 的本地化字符串。
        /// </summary>
        public static string PleaseFillInTheCorrectIntegerValue {
            get {
                return ResourceManager.GetString("PleaseFillInTheCorrectIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板文件路径不能为空! 的本地化字符串。
        /// </summary>
        public static string TemplateFilePathCannotBeEmpty {
            get {
                return ResourceManager.GetString("TemplateFilePathCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在模板下拉选项中！ 的本地化字符串。
        /// </summary>
        public static string ThereAreNoTemplateDropDownOptions {
            get {
                return ResourceManager.GetString("ThereAreNoTemplateDropDownOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误数据 的本地化字符串。
        /// </summary>
        public static string WrongData {
            get {
                return ResourceManager.GetString("WrongData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
